echo "Server Stats"
echo "CPU Usage: $(top -b -n 1 | grep "Cpu(s)" | awk '{print $2 + $4}')%"
echo "Memory Usage: $(free -m | grep "Mem:" | awk '{print $3/$2 * 100}')%"
echo "Disk Usage: $(df -h | grep "/dev/sda1" | awk '{print $5}')"
echo "Uptime: $(uptime -p | sed 's/up //')"
echo "Last Boot: $(who -b | awk '{print $3, $4}')"
echo "Users: $(who | wc -l)"
echo "IP Address: $(hostname -I)"
echo "Hostname: $(hostname)"
echo "OS: $(lsb_release -d | awk '{print $2, $3}')"